### PR TITLE
fix #10; add selects chromosome proportional to chromosome lengths

### LINKED ISSUE #10: Add does not add proportionally to each chromosome
Add needs to consider the length of each chromosome instead of selecting a random chromosome with the same chance of each chromosome being selected.

### PR DESCRIPTION
**Pull request by aaron-gu**

### CODE REVIEW

**Comment by aaron-gu** [comment]
@hyunjaecho94 I can't add you as reviewer, but please see the PR and leave any comments you have!

**Comment by nsheff** [comment]
merge feature branches to dev;
merge dev to master for release.

**Comment by nsheff** [comment]
this is good -- probably just role the 'valid regions' concept into this somehow?

**Comment by aaron-gu** [comment]
this PR fixes #20 as well

**Comment by aaron-gu** [comment]
"Valid regions" #23 will be addressed in a separate PR

**Pull request merged**
