### PR TITLE
Version 1.1.0

### PR DESCRIPTION
**Pull request by aaron-gu**
TODO:

- [ ] update changelog with date (https://github.com/databio/bedshift/blob/master/docs/changelog.md)
- [ ] update changelog with list of all changed things
- [ ] release to pypi (should be automatic with a github action when releasing on github after PR is merged)

### CODE REVIEW

**Comment by nsheff** [comment]
what's the plan for this release?

**Comment by aaron-gu** [comment]
If you ran the pep projects without any issues, I will release this.

**Comment by aaron-gu** [comment]
Are there any more changes in the works?

**Comment by nsheff** [comment]
I don't have anything planned.

**Comment by nsheff** [comment]
let's go for release then (once you push that column number fix and the release info listed above)

**Pull request merged**
